repos:
  - repo: local
    hooks:
      # check article: https://zhauniarovich.com/post/2020/2020-06-clearing-jupyter-output/
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace