site_name: elastipy
#theme: readthedocs
theme: material

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import sys
            - import os
            - sys.path.insert(0, os.path.abspath('..'))
          selection:
            docstring_style: google
            #restructured-text
            inherited_members: true

#nav:
#  - Home: index.md
#  - About: about.md
